import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="ShipSense", layout="wide", page_icon="🚚")

PREDICTIONS_PATH = "data/processed/predictions.csv"


@st.cache_data
def load_predictions(path: str) -> pd.DataFrame:
    """Loads the scored predictions CSV once per session (cached)."""
    df = pd.read_csv(path)
    required_cols = {
        "order_id", "region_id", "hour_of_day", "predicted_eta_minutes",
        "promised_eta_minutes", "delay_minutes", "risk_status", "top_delay_factor",
    }
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"predictions.csv is missing expected columns: {missing}")
    return df


def apply_filters(df: pd.DataFrame, region, risk, hour_range) -> pd.DataFrame:
    """Applies sidebar filters to the predictions DataFrame."""
    filtered = df.copy()

    if region != "All":
        filtered = filtered[filtered["region_id"] == region]

    if risk != "All":
        filtered = filtered[filtered["risk_status"] == risk]

    filtered = filtered[
        (filtered["hour_of_day"] >= hour_range[0])
        & (filtered["hour_of_day"] <= hour_range[1])
    ]

    return filtered


# ---------- Header ----------
st.title("🚚 ShipSense")
st.caption("AI-powered delivery risk & ETA intelligence")

tab1, tab2, tab3 = st.tabs(["Operations Dashboard", "Demand Heatmap", "Executive Summary"])

# Shared data load (used by all three tabs)
data_load_error = None
df = None
if not os.path.exists(PREDICTIONS_PATH):
    data_load_error = (
        "Predictions data not found. Run `python src/predict.py` first "
        "to generate `data/processed/predictions.csv`."
    )
else:
    try:
        with st.spinner("Loading delivery data..."):
            df = load_predictions(PREDICTIONS_PATH)
    except (pd.errors.EmptyDataError, pd.errors.ParserError) as e:
        data_load_error = (
            "Could not read the predictions file — it appears to be corrupted "
            f"or empty. Try regenerating it with `python src/predict.py`.\n\n"
            f"Technical detail: {e}"
        )
    except ValueError as e:
        data_load_error = (
            "The predictions file is missing expected columns. It may have "
            f"been generated by an older version of the pipeline.\n\n"
            f"Technical detail: {e}"
        )
    except Exception as e:
        data_load_error = f"An unexpected error occurred while loading data: {e}"

# ================= TAB 1: OPERATIONS DASHBOARD =================
with tab1:
    if data_load_error:
        st.error(data_load_error)
    else:
        # --- Filters ---
        st.subheader("Filters")
        col1, col2, col3 = st.columns([1, 1, 2])

        with col1:
            region_options = ["All"] + sorted(df["region_id"].unique().tolist())
            selected_region = st.selectbox("Area / Region", region_options, key="ops_region")

        with col2:
            selected_risk = st.selectbox("Risk Status", ["All", "At Risk", "On Track"], key="ops_risk")

        with col3:
            selected_hours = st.slider("Hour of Day", 0, 23, (0, 23), key="ops_hours")

        filtered_df = apply_filters(df, selected_region, selected_risk, selected_hours)

        st.divider()

        # --- Summary strip ---
        total = len(filtered_df)
        if total == 0:
            st.warning("No deliveries match the current filters. Try widening your selection.")
        else:
            at_risk_count = (filtered_df["risk_status"] == "At Risk").sum()
            on_track_count = total - at_risk_count
            at_risk_pct = (at_risk_count / total) * 100

            m1, m2, m3 = st.columns(3)
            m1.metric("Total Orders", f"{total:,}")
            m2.metric("🔴 At Risk", f"{at_risk_count:,}", f"{at_risk_pct:.1f}%")
            m3.metric("🟢 On Track", f"{on_track_count:,}", f"{100 - at_risk_pct:.1f}%")

            st.divider()

            # --- Table ---
            st.subheader("Deliveries")

            display_df = filtered_df.copy()
            display_df["Risk"] = display_df["risk_status"].map(
                {"At Risk": "🔴 At Risk", "On Track": "🟢 On Track"}
            )
            display_df["Predicted ETA (min)"] = display_df["predicted_eta_minutes"].round(1)
            display_df["Promised ETA (min)"] = display_df["promised_eta_minutes"].round(1)
            display_df["Delay (min)"] = display_df["delay_minutes"].round(1)
            display_df["Top Delay Factor"] = display_df["top_delay_factor"].fillna("—")

            display_df = display_df.rename(columns={
                "order_id": "Order ID", "region_id": "Region", "hour_of_day": "Hour",
            })
            show_cols_renamed = [
                "Order ID", "Region", "Hour",
                "Predicted ETA (min)", "Promised ETA (min)", "Delay (min)",
                "Risk", "Top Delay Factor",
            ]

            display_df = display_df.sort_values("Delay (min)", ascending=False)

            st.dataframe(
                display_df[show_cols_renamed].head(500),
                use_container_width=True,
                height=450,
            )
            if total > 500:
                st.caption(f"Showing top 500 of {total:,} matching deliveries (sorted by delay).")

# ================= TAB 2: DEMAND HEATMAP =================
with tab2:
    if data_load_error:
        st.error(data_load_error)
    else:
        st.subheader("Order Density by Hour and Region")
        st.caption("Darker cells indicate higher order volume. Use this to anticipate staffing and routing needs.")

        heatmap_data = (
            df.groupby(["region_id", "hour_of_day"])
            .size()
            .reset_index(name="order_count")
        )

        top_regions = df["region_id"].value_counts().head(15).index.tolist()
        heatmap_data = heatmap_data[heatmap_data["region_id"].isin(top_regions)]

        pivot = heatmap_data.pivot(index="region_id", columns="hour_of_day", values="order_count").fillna(0)
        pivot = pivot.reindex(top_regions)

        fig = px.imshow(
            pivot,
            labels=dict(x="Hour of Day", y="Region", color="Orders"),
            color_continuous_scale="Blues",
            aspect="auto",
        )
        fig.update_layout(height=500, margin=dict(l=10, r=10, t=30, b=10))
        st.plotly_chart(fig, use_container_width=True)

        st.divider()

        st.subheader("Overall Order Volume by Hour")
        hourly_totals = df.groupby("hour_of_day").size().reset_index(name="orders")
        fig2 = px.bar(
            hourly_totals, x="hour_of_day", y="orders",
            labels={"hour_of_day": "Hour of Day", "orders": "Total Orders"},
            color_discrete_sequence=["#1C7293"],
        )
        fig2.update_layout(height=350, margin=dict(l=10, r=10, t=10, b=10))
        st.plotly_chart(fig2, use_container_width=True)

        peak_hour = hourly_totals.loc[hourly_totals["orders"].idxmax(), "hour_of_day"]
        st.caption(f"Peak order volume occurs around **{int(peak_hour):02d}:00**.")

# ================= TAB 3: EXECUTIVE SUMMARY =================
with tab3:
    if data_load_error:
        st.error(data_load_error)
    else:
        st.subheader("Delivery Health Overview")

        total_orders = len(df)
        avg_eta = df["predicted_eta_minutes"].mean()
        at_risk_df = df[df["risk_status"] == "At Risk"]
        at_risk_pct = (len(at_risk_df) / total_orders) * 100
        avg_delay_at_risk = at_risk_df["delay_minutes"].mean() if len(at_risk_df) > 0 else 0

        k1, k2, k3, k4 = st.columns(4)
        k1.metric("Total Orders", f"{total_orders:,}")
        k2.metric("Avg Predicted ETA", f"{avg_eta:.1f} min")
        k3.metric("% At Risk", f"{at_risk_pct:.1f}%")
        k4.metric("Avg Delay (At-Risk Orders)", f"{avg_delay_at_risk:.1f} min")

        st.divider()

        col_left, col_right = st.columns([1, 1])

        with col_left:
            st.subheader("Top Factors Correlated with Delay")
            factor_counts = at_risk_df["top_delay_factor"].value_counts().head(6)
            if len(factor_counts) > 0:
                fig3 = px.bar(
                    x=factor_counts.values, y=factor_counts.index, orientation="h",
                    labels={"x": "At-Risk Orders", "y": ""},
                    color_discrete_sequence=["#065A82"],
                )
                fig3.update_layout(height=320, margin=dict(l=10, r=10, t=10, b=10), yaxis=dict(autorange="reversed"))
                st.plotly_chart(fig3, use_container_width=True)
            else:
                st.info("No at-risk orders in the current dataset to analyze.")

        with col_right:
            st.subheader("Risk Breakdown")
            risk_counts = df["risk_status"].value_counts()
            fig4 = px.pie(
                values=risk_counts.values, names=risk_counts.index,
                color=risk_counts.index,
                color_discrete_map={"At Risk": "#E74C3C", "On Track": "#2ECC71"},
                hole=0.5,
            )
            fig4.update_layout(height=320, margin=dict(l=10, r=10, t=10, b=10))
            st.plotly_chart(fig4, use_container_width=True)

        st.divider()

        top_factor_name = factor_counts.index[0] if len(factor_counts) > 0 else "N/A"
        st.markdown(
            f"**Summary:** Today, **{at_risk_pct:.1f}%** of deliveries are trending at-risk, "
            f"with an average predicted delay of **{avg_delay_at_risk:.1f} minutes** beyond the "
            f"promised time. The factor most strongly associated with these delays is **{top_factor_name}**."
        )

# ---------- Footer ----------
st.divider()
st.markdown(
    "<div style='text-align: center; color: gray; font-size: 0.85em;'>"
    "Built with Claude as part of the AB Talks 60-Day Claude AI Challenge."
    "</div>",
    unsafe_allow_html=True,
)